### ISSUE TITLE
Linting errors not returning the list of errors

### ISSUE THREAD

**Issue by MarcioMeier** [flaviostutz/cdk-practical-constructs#2]
## What's broken?
CDK linting errors

## Version used
0.2.0

## Context
I just bootstrapped my aws account and tried to deploy a stack with a single `BaseNodeJsFunction` construct and integrated it with the api gateway constrcut `OpenApiGatewayLambda`.

When i run the synth i get the following lint error without a proper explanation of what is wrong

![image (5)](https://github.com/flaviostutz/cdk-practical-constructs/assets/34343596/89f2dc06-c5ae-4336-abb4-2be252c48f72)

This is an intermitent error, which means that sometimes it just deploy, and sometimes it just break.
Rerunning after breaking, it deploys. so far, it never happened twice in a row

**Comment by flaviostutz** [comment]
It always happens after you cleanup the CDK output dir, or it's intermittent too?

**Comment by MarcioMeier** [comment]
Just confirmed that it also happens in the latest version 0.3.0

**Comment by flaviostutz** [comment]
Is it intermittent or consistent (I mean, everytime you cleanup the dir it happens, or sometimes yes, sometimes no?)?

**Comment by MarcioMeier** [comment]
It is intermitent.

But I think it was solved already but not yet published...
Since I linked the package with the main branch it stopped giving this error.
I still need further test a few scenarios though

**Comment by MarcioMeier** [comment]
The issue is timeout, it is currently set to [10 seconds](https://github.com/flaviostutz/cdk-practical-constructs/blob/c393163717f3e8083ae047dd063dd52479c33fd8/lib/src/utils/openapi-lint.ts#L55) but my machine doesn't handle it within 10 seconds
