### ISSUE TITLE
Destroy not deleting log groups

### ISSUE THREAD

**Issue by MarcioMeier** [flaviostutz/cdk-practical-constructs#3]
## What's broken?
The construct is not deleting the log groups when running cdk destroy.

## Version used

0.3.0

## Context

When deleting the stack, the stack is properly removed from the cloudformation, but when trying to deploy it again, i get the following error:
![image](https://github.com/flaviostutz/cdk-practical-constructs/assets/34343596/d0012352-3d4b-484b-95aa-9beced9b80c5)

**Comment by MarcioMeier** [comment]
It seems that we're having an issue to build the log groups names, it is not using the whole stage into the name
<img width="671" alt="image" src="https://github.com/flaviostutz/cdk-practical-constructs/assets/34343596/4186bb49-7329-4ad8-8c8f-02fb40d234e8">


The stack name is `dossier-service-dev-marcio` so I would expect it to create with `dossier-service-dev-marcio-${something}`, but it created with `dossier-service-dev-marci-${something}` instead.

**Comment by MarcioMeier** [comment]
There is also this generic log group named `/aws/lambda/Wso2ApiCustomResourceFunction-dev` that must have the stack name concatenated to it

**Comment by flaviostutz** [comment]
In general, the retainment of the log groups by default is on purpose to avoid losing data from execution logs. For example, for the Lambda construct, you can use logGroupRemovalPolicy to change it.
In this case it seems we need to work a bit better on the defaults of the log groups related to the API Gateway too.

**Comment by flaviostutz** [comment]
In relation to "dossier-service-dev-marci-${something}", we are limiting the size of the prefix name (with the stack name) in order to limit a bit the size of the resource name so it doesn't get too big. If this is too small, we can discuss increasing it :)

**Comment by flaviostutz** [comment]
Is this issue still active after the recent resource naming refactoring you did?

**Comment by MarcioMeier** [comment]
No, we can close this one!
