### ISSUE TITLE
Don't create a default Security Group

### ISSUE THREAD

**Issue by erik-am** [flaviostutz/cdk-practical-constructs#44]
The `BaseNodeJsFunction` creates a new, default security group for each lambda.

This is actually not a recommended practice, because AWS will create a new ENI and use up an IP address in the subnet, for each _unique combination of subnet + security group_.
So attaching a new, unique security group to each new lambda, means that each lambda needs its own ENI and IP address and you will hit limits at some point.

![image](https://github.com/user-attachments/assets/d905d7ec-e988-4a4e-b251-a0d3ade1bb88)

See https://aws.amazon.com/blogs/compute/announcing-improved-vpc-networking-for-aws-lambda-functions/ for more details on how this works.

## Feature request

I would remove the default security group option completely.

Or at the very least, making it controllable with a boolean. And set the default to `false`.

**Comment by flaviostutz** [comment]
Great article! Thanks for that!
