### ISSUE TITLE
Improvements for enabling API Gateway caching

### ISSUE THREAD

**Issue by SaltyAga** [flaviostutz/cdk-practical-constructs#47]
## 1. Fix for deployOptions

Caching parameters  for API gateway can be defined in deployOptions, which is a property from OpenApiGatewayLambdaProps.
[Stage Options](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_apigateway/StageOptions.html)

Currently, deployOptions, that have been passed when creating a new OpenApiGatewayLambda, will be ignored if accessLogEnable is true:
[Link to the code](https://github.com/flaviostutz/cdk-practical-constructs/blob/547ac09940fdad151f1f32dd26fe914a1dbf7583/lib/src/apigateway/openapi-gateway-lambda.ts#L173)
```
if (props.accessLogEnable && props.deployOptions) {
    throw new Error("When 'accessLogEnable' is defined, 'deployOptions' cannot be defined");
  }
```

### A proposed change
```
const addLogGroupForTracing = (
  scope: Construct,
  props: OpenApiGatewayLambdaProps,
): { deployOptions: StageOptions; logGroupAccessLog?: LogGroup } => {
  if (props.accessLogEnable) {
    const logGroupAccessLog = new LogGroup(scope, 'AccessLogGroup', {
      logGroupName: `apigateway-accesslogs-${scope.node.id}`,
      retention: props.accessLogRetention,
    });

    const deployOptionsAccessLog: StageOptions = {
      ...props.deployOptions,
      accessLogDestination:
        props.deployOptions?.accessLogDestination ?? new LogGroupLogDestination(logGroupAccessLog),
      accessLogFormat:
        props.deployOptions?.accessLogFormat ?? AccessLogFormat.jsonWithStandardFields(),
      loggingLevel: props.deployOptions?.loggingLevel ?? MethodLoggingLevel.INFO,
      dataTraceEnabled: props.deployOptions?.dataTraceEnabled ?? false,
      tracingEnabled: props.deployOptions?.tracingEnabled ?? true,
      metricsEnabled: props.deployOptions?.metricsEnabled ?? true,
    };

    return { deployOptions: deployOptionsAccessLog, logGroupAccessLog };
  }

  return {
    deployOptions: props.deployOptions ?? {
      metricsEnabled: true,
    },
  };
};
```
Or if accessLogEnable property is intended to have more weight, we can just remove the throw statement and keep the rest without change, but it should be properly documented that some of deployOptions will be rewritten in case props.accessLogEnable = true.
```
const addLogGroupForTracing = (
  scope: Construct,
  props: OpenApiGatewayLambdaProps,
): { deployOptions: StageOptions; logGroupAccessLog?: LogGroup } => {
  if (props.accessLogEnable && props.deployOptions) {
    throw new Error("When 'accessLogEnable' is defined, 'deployOptions' cannot be defined");
  }

  if (props.accessLogEnable) {
    const logGroupAccessLog = new LogGroup(scope, 'AccessLogGroup', {
      logGroupName: `apigateway-accesslogs-${scope.node.id}`,
      retention: props.accessLogRetention,
    });

    const deployOptionsAccessLog: StageOptions = {
      ...props.deployOptions,
      accessLogDestination: new LogGroupLogDestination(logGroupAccessLog),
      accessLogFormat: AccessLogFormat.jsonWithStandardFields(),
      loggingLevel: MethodLoggingLevel.INFO,
      dataTraceEnabled: false,
      tracingEnabled: true,
      metricsEnabled: props.deployOptions?.metricsEnabled ?? true,
    };

    return { deployOptions: deployOptionsAccessLog, logGroupAccessLog };
  }
```

## 2. Add lambda integration options
We may also need to set cacheKeyParameters, which are part of the [API Gateway integration](https://docs.aws.amazon.com/apigateway/latest/api/API_Integration.html) object.

### Proposal
1) Add [IntegrationOptions](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.IntegrationOptions.html) to LambdaOperation type
```
export type LambdaOperation = {
  routeConfig: RouteConfig;
  lambdaAlias: LambdaAlias;
  awsExtensions?: AwsExtensions;
  integrationOptions?: IntegrationOptions;
};
```
2) Pass integration options to jsonObj['x-amazon-apigateway-integration']
https://github.com/flaviostutz/cdk-practical-constructs/blob/547ac09940fdad151f1f32dd26fe914a1dbf7583/lib/src/apigateway/openapi-gateway-lambda.ts#L309

```
jsonObj['x-amazon-apigateway-integration'] = {
            ...lambdaOp.integrationOptions,
            // We need to use a api gw lambda invocation function to invocate the lambda we are integrating
            // https://stackoverflow.com/a/50696321
            uri: `arn:aws:apigateway:${awsRegion}:lambda:path/2015-03-31/functions/${lambdaOp.lambdaAlias.functionArn}/invocations`,
            // "passthroughBehavior": "when_no_match",
            httpMethod: 'POST',
            type: 'AWS_PROXY',
          };
```

**Comment by SaltyAga** [comment]
In our tool we can create, read, update and delete messages.

- For the GET calls there is ApiGateway cache enabled for 1 hour, so that all the calls from the FE portals are cached and not unnecessarily triggering the lambda.

This can be done by passing deployOptions to apigateway, for example:
```
deployOptions: {
        cachingEnabled: true,
        methodOptions: {
          '/messages/GET': {
            cachingEnabled: true,
            cacheTtl: Duration.seconds(3600),
          }
        }
      },
```

- To make sure we get the correct messages for different portals, we need to specify cacheKeyParameters. So if the messages are not cached for a particular portal, we retrieve them from the database. We also need to specify requestParameters:
https://stackoverflow.com/questions/75535102/aws-api-gateway-caching-only-if-no-query-parameters-in-path
These parameters are a part of [x-amazon-apigateway-integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html).

- We also need to flush the cache every time there is a POST/PUT/DELETE request. That could be implemented after apigateway has been created by attaching cache delete policies to our lambdas. So no changes are needed for this in the practical-constructs.

**Comment by flaviostutz** [comment]
> In our tool we can create, read, update and delete messages.
> 
> * For the GET calls there is ApiGateway cache enabled for 1 hour, so that all the calls from the FE portals are cached and not unnecessarily triggering the lambda.
> 
> This can be done by passing deployOptions to apigateway, for example:
> 
> ```
> deployOptions: {
>         cachingEnabled: true,
>         methodOptions: {
>           '/messages/GET': {
>             cachingEnabled: true,
>             cacheTtl: Duration.seconds(3600),
>           }
>         }
>       },
> ```
> 
> * To make sure we get the correct messages for different portals, we need to specify cacheKeyParameters. So if the messages are not cached for a particular portal, we retrieve them from the database. We also need to specify requestParameters:
>   https://stackoverflow.com/questions/75535102/aws-api-gateway-caching-only-if-no-query-parameters-in-path
>   These parameters are a part of [x-amazon-apigateway-integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html).
> * We also need to flush the cache every time there is a POST/PUT/DELETE request. That could be implemented after apigateway has been created by attaching cache delete policies to our lambdas. So no changes are needed for this in the practical-constructs.

Could you explain better how do you attach the cache delete policies? Maybe with an example? Is it done manually?

**Comment by SaltyAga** [comment]
1) _"Could you explain better how do you attach the cache delete policies? Maybe with an example? Is it done manually?"_

Initially, I wanted to include it in the apigateway construct, but for this I would need another field in lambdaOperation to indicate whether lambda is allowed to delete cache from the apigateway, and, in general, it seemed quite hardcoded.

I am adding it in in our stack after the apigateway is defined, for example:
```
const apigw = new OpenApiGatewayLambda(this, ....);
const restApiId = apigw.specRestApi.restApiId;

const apiGatewayDeletePolicyStatement = new PolicyStatement({
  effect: Effect.ALLOW,
  actions: ['apigateway:DELETE'],
  resources: [
    `arn:aws:apigateway:${awsRegion}::/restapis/${restApiId}/stages/${props.stage}/cache/data`,
  ],
});

const apiGatewayDeletePolicy = new Policy(this, 'ApiGatewayDeletePolicy', {
  statements: [apiGatewayDeletePolicyStatement],
});

lambda.lambdaFunction.nodeJsFunction.role?.attachInlinePolicy(apiGatewayDeletePolicy);
```

2. In our case all the users should see the same message.
